// Silk Road campaign content, Afro-Eurasia c. 900 A.D.
// Map coordinates are in viewBox 0..2400 (W) x 0..1200 (H). Lat/lon roughly:
//   x≈120 → 10°W (Atlantic edge), x≈2280 → 135°E (Korea/Japan)
//   y≈140 → 60°N (Rus',Scandinavia edge), y≈1080 → 10°N (Arabia/S.India edge)

window.SILKROAD_DATA = {
  // Named empire/khanate regions — shown as LARGE labels
  regions: [
    { id: "rus",      label: "RUS'",              x: 1040, y: 290, size: 36, sub: "of the Varangians" },
    { id: "pechenegs",label: "PECHENEGS",         x: 1180, y: 340, size: 28, sub: null },
    { id: "khazars",  label: "KHAZARS",           x: 1300, y: 380, size: 30, sub: null },
    { id: "byz",      label: "BYZANTIUM",         x: 970,  y: 440, size: 30, sub: "Ῥωμανία" },
    { id: "abbasid",  label: "ABBASID CALIPHATE", x: 1220, y: 560, size: 36, sub: null },
    { id: "fatimid",  label: "FĀṬIMID IFRĪQIYA",  x: 870,  y: 600, size: 22, sub: null },
    { id: "andalus",  label: "AL-ANDALUS",        x: 490,  y: 540, size: 24, sub: null },
    { id: "ghuzz",    label: "GHUZZ",             x: 1440, y: 500, size: 30, sub: "the Oghuz steppe" },
    { id: "turgesh",  label: "TÜRGESH",           x: 1560, y: 450, size: 28, sub: null },
    { id: "karluks",  label: "KARLUKS",           x: 1660, y: 420, size: 28, sub: null },
    { id: "kimeks",   label: "KIMAKS",            x: 1560, y: 360, size: 24, sub: null },
    { id: "kyrgyz",   label: "KYRGYZ",            x: 1760, y: 300, size: 24, sub: null },
    { id: "uyghur",   label: "UYGHUR KHAGANATE",  x: 1860, y: 440, size: 30, sub: "qaghanate of the steppe" },
    { id: "tibet",    label: "TIBETAN EMPIRE",    x: 1760, y: 640, size: 28, sub: null },
    { id: "tang",     label: "TANG DYNASTY",      x: 2080, y: 600, size: 36, sub: "天朝 — the Celestial" },
    { id: "nanzhao",  label: "NAN-ZHAO",          x: 2020, y: 780, size: 22, sub: null },
    { id: "tufan",    label: "PRATĪHĀRAS",        x: 1640, y: 780, size: 24, sub: null },
    { id: "palas",    label: "PĀLAS",             x: 1820, y: 780, size: 22, sub: null },
    { id: "rashtra",  label: "RĀṢṬRAKŪṬA",        x: 1620, y: 900, size: 22, sub: null },
    { id: "kabul",    label: "KĀBUL-SHĀHĪ",       x: 1530, y: 640, size: 22, sub: null,
      image: "images/places/kabul.png" },
  ],

  // Water labels
  seas: [
    { id: "med", label: "MARE INTERNUM", x: 880, y: 560, size: 22 },
    { id: "black", label: "Black Sea", x: 1120, y: 430, size: 16 },
    { id: "caspian", label: "Caspian Sea", x: 1310, y: 450, size: 14 },
    { id: "aral", label: "Aral Sea", x: 1440, y: 420, size: 12 },
    { id: "persian", label: "Persian Gulf", x: 1290, y: 680, size: 14 },
    { id: "red", label: "Red Sea", x: 1160, y: 740, size: 14 },
    { id: "arabian", label: "ARABIAN SEA", x: 1440, y: 880, size: 20 },
    { id: "bengal", label: "Gulf of Bengal", x: 1800, y: 900, size: 14 },
    { id: "south-china", label: "South China Sea", x: 2180, y: 840, size: 14 },
    { id: "atlantic", label: "MARE OCEANUM", x: 280, y: 500, size: 22 },
  ],

  // Named deserts (shown as sand-pattern regions + labels)
  deserts: [
    { id: "sahara",    label: "SAHARA",          x: 780,  y: 780, w: 600, h: 100 },
    { id: "rubal",     label: "Rub' al-Khālī",   x: 1280, y: 840, w: 220, h: 80 },
    { id: "kyzylkum",  label: "Kyzylkum Desert", x: 1440, y: 480, w: 160, h: 50 },
    { id: "karakum",   label: "Kara-Kum Desert", x: 1400, y: 540, w: 140, h: 40 },
    { id: "taklamakan",label: "TAKLAMAKAN",      x: 1840, y: 530, w: 240, h: 70 },
    { id: "gobi",      label: "GOBI DESERT",     x: 2060, y: 470, w: 260, h: 70 },
    { id: "thar",      label: "Thar Desert",     x: 1620, y: 820, w: 120, h: 50 },
  ],

  // Mountain ranges (stylized hatched zones + italicized labels)
  mountains: [
    { id: "alps",    label: "Alps",         path: "M 820 500 Q 900 490 980 510" },
    { id: "caucasus",label: "Caucasus mts.", path: "M 1220 450 Q 1280 445 1340 455" },
    { id: "zagros", label: "Zagros mts.", path: "M 1240 580 Q 1300 610 1340 650" },
    { id: "pamir",  label: "Pamir mts.", path: "M 1640 570 Q 1680 580 1720 600" },
    { id: "tianshan", label: "Tien Shan mts.", path: "M 1700 500 Q 1780 490 1860 510" },
    { id: "kunlun", label: "Kunlun mts.", path: "M 1800 640 Q 1880 650 1960 660" },
    { id: "himalaya", label: "Himalayan mts.", path: "M 1720 720 Q 1820 730 1920 740" },
    { id: "hindukush", label: "Hindū Kush", path: "M 1560 640 Q 1610 660 1650 680" },
    { id: "altai",  label: "Altai mts.",   path: "M 1780 360 Q 1860 370 1940 390" },
    { id: "qilian", label: "Qilian mts.", path: "M 2000 580 Q 2060 590 2120 600" },
    { id: "atlas",  label: "Atlas mts.",   path: "M 620 640 Q 690 645 760 655" },
  ],

  // Rivers (thin blue lines)
  rivers: [
    { id: "rhine",   path: "M 820 430 Q 830 490 840 560", label: "Rhine",    lx: 830,  ly: 460 },
    { id: "danube",  path: "M 870 480 Q 960 490 1080 470", label: "Danube",  lx: 980,  ly: 480 },
    { id: "dnieper", path: "M 1120 280 Q 1100 360 1110 430", label: "Dnieper", lx: 1095, ly: 360 },
    { id: "volga",   path: "M 1350 280 Q 1320 370 1310 450", label: "Volga",  lx: 1320, ly: 370 },
    { id: "don",     path: "M 1240 320 Q 1220 390 1240 440", label: "Don",    lx: 1220, ly: 390 },
    { id: "euphrates",path: "M 1200 470 Q 1230 540 1270 620", label: "Euphrates", lx: 1195, ly: 540 },
    { id: "tigris",  path: "M 1230 470 Q 1260 540 1280 620", label: "Tigris", lx: 1275, ly: 540 },
    { id: "nile",    path: "M 1080 840 Q 1080 750 1090 660", label: "Nile",   lx: 1070, ly: 750 },
    { id: "oxus",    path: "M 1600 560 Q 1540 510 1480 470", label: "Oxus (Amū Darya)", lx: 1540, ly: 490 },
    { id: "jaxartes",path: "M 1640 500 Q 1580 460 1510 430", label: "Jaxartes (Sīr Darya)", lx: 1580, ly: 440 },
    { id: "indus",   path: "M 1580 660 Q 1580 760 1600 860", label: "Indus", lx: 1570, ly: 760 },
    { id: "ganges",  path: "M 1700 780 Q 1770 800 1840 820", label: "Ganges", lx: 1770, ly: 795 },
    { id: "yellow",  path: "M 2000 520 Q 2080 580 2160 640 Q 2200 680 2220 720", label: "Huang He", lx: 2100, ly: 610 },
    { id: "yangtze", path: "M 2000 640 Q 2080 720 2180 770 Q 2220 790 2260 800", label: "Chang Jiang", lx: 2120, ly: 740 },
  ],

  // Cities
  places: [
    // Great cities
    { id: "constantinople", name: "Constantinople", region: "Byzantium", x: 1060, y: 460,
      kind: "great-city",
      blurb: "The Queen of Cities. Byzantine bulwark of the West, golden domes crowning the Bosphorus. Greek merchants trade silks from the East for Frankish silver; eunuchs and patriarchs whisper of a relic lost beyond the Oxus.",
      image: "images/places/constantinople.png" },
    { id: "baghdad", name: "Baghdad", region: "Abbasid Caliphate", x: 1270, y: 580,
      kind: "great-city",
      blurb: "The Round City of Peace, seat of the Abbasid Caliphate. The House of Wisdom glows through the night with astronomers, poets, and translators. Our party began here, summoned by a vizier whose name must not be written.",
      image: "images/places/baghdad.png" },
    { id: "samarkand", name: "Samarkand", region: "Transoxiana (Ghuzz frontier)", x: 1540, y: 560,
      kind: "great-city",
      blurb: "Jewel of the Sogdian plain. Its bazaars ring with forty tongues. Papermakers guard secrets worth kingdoms. A caravanserai here conceals the Silent Door.",
      image: "images/places/samarkand.png" },
    { id: "changan", name: "Chang'an", region: "Tang Dynasty", x: 2180, y: 620,
      kind: "great-city",
      blurb: "End of the Road. The Tang capital is in late decline — eunuch factions, provincial warlords, poets drinking to forget. The Emperor's grandson collects foreign demons in a garden of iron.",
      image: "images/places/changan.png" },

    // Major cities
    { id: "bukhara",     name: "Bukhara",     region: "Transoxiana", x: 1500, y: 540, kind: "city",
      blurb: "The Dome of Islam in the East. Samanid emirs host theologians and smugglers alike. A shrine to an older power still stands where the minaret will one day rise.",
      image: "images/places/bukhara.png" },
    { id: "kashgar",     name: "Kashgar",     region: "Tarim Basin", x: 1760, y: 560, kind: "city",
      blurb: "Oasis gate between the Pamirs and the desert. Here the Southern and Northern Silk Roads braid together. The Sunday market has run uninterrupted, they say, since before the Flood.",
      image: "images/places/kashgar.png" },
    { id: "dunhuang",    name: "Dunhuang",    region: "Hexi Corridor", x: 2020, y: 580, kind: "city",
      blurb: "The Blazing Beacon. Mogao's painted caves hide ten thousand buddhas — and one that is not a buddha at all. The monk Hongbian keeps a library sealed behind a false wall.",
      image: "images/places/dunhuang.png" },
    { id: "khotan",      name: "Khotan",      region: "Tarim Basin", x: 1820, y: 620, kind: "city",
      blurb: "City of white jade and sericulture. Buddhist kingdom claiming descent from Ashoka. Beware the jade-cutters' guild — they answer to older masters.",
      image: "images/places/khotan.png" },
    { id: "merv",        name: "Merv",        region: "Khorasan", x: 1420, y: 570, kind: "city",
      blurb: "Mother of Cities. Walled oasis where Zoroastrian fire-keepers, Nestorian priests and Sufi wanderers share the same well.",
      image: "images/places/merv.png" },
    { id: "balkh",       name: "Balkh",       region: "Khorasan", x: 1520, y: 620, kind: "city",
      blurb: "Umm al-Bilad. Ruins of Nawbahar, greatest Buddhist temple west of the Pamirs, lie quiet under the snow. Something beneath them is not quiet.",
      image: "images/places/balkh.png" },
    { id: "nishapur",    name: "Nishapur",    region: "Khorasan", x: 1400, y: 610, kind: "city",
      blurb: "A great Khorasanian city of libraries under Sāmānid rule. We found it a necessary stop on the road east, its turquoise domes a welcome sight after the steppe.",
      image: "images/places/nishapur.png"  },
    { id: "rey",         name: "Rey",         region: "Jibāl", x: 1320, y: 580, kind: "city",
      blurb: "One of the great frontier cities between empires, known for its theologians and coppersmiths. It stands as a bulwark and a crossroads, ever watchful.",
      image: "images/places/rey.png"  },
    { id: "shiraz",      name: "Shiraz",      region: "Fārs", x: 1320, y: 700, kind: "city",
      blurb: "Famed for its poets and gardens, a paradise city of the Buyid emirs. We sought rest here after Merv, but found our own purposes: a master's scimitar for Bansi, and a dark cult purged by Eskil. Even so, the vampire Paul found Giovanni's throat in a silent house of old things.",
      image: "images/places/shiraz.png"  },
    { id: "damascus",    name: "Damascus",    region: "al-Shām", x: 1150, y: 580, kind: "city",
      blurb: "The old capital of the Umayyad caliphs, still a great city of the empire. It is the gateway between Egypt and Mesopotamia, its markets filled with the wealth of both.",
      image: "images/places/damascus.png"  },
    { id: "jerusalem",   name: "Jerusalem",   region: "al-Shām", x: 1130, y: 610, kind: "city",
      blurb: "A holy city to three faiths, held under the Caliph's peace. The great Dome of the Rock now stands over the Temple Mount, but the quarters of Christians and Jews hold to their own ways.",
      image: "images/places/jerusalem.png"  },
    { id: "alexandria",  name: "Alexandria",  region: "Egypt", x: 1060, y: 620, kind: "city",
      blurb: "The great lighthouse of Pharos still stands, but the famous library is a ghost. It is a key Egyptian port, ruled by the Tūlūnid emirs.",
      image: "images/places/alexandria.png"  },
    { id: "cairo",       name: "Fusṭāṭ",      region: "Egypt", x: 1080, y: 660, kind: "city",
      blurb: "This is Fusṭāṭ, the garrison-city built by the first conquerors on the Nile. It is the capital of Egypt, a sprawling city of soldiers, governors, and merchants.",
      image: "images/places/cairo.png"  },
    { id: "aden",        name: "Aden",        region: "Yemen", x: 1200, y: 900, kind: "city",
      blurb: "The port on the Arabian Sea where the caravan-queen Hind received and betrayed us. It is the gate between the Red Sea and the Indian Ocean, and its markets thrive on the exchange.",
      image: "images/places/aden.png"  },
    { id: "mecca",       name: "Mecca",       region: "Ḥijāz", x: 1180, y: 790, kind: "city",
      blurb: "The holy city, the heart of the faith. Though ruled from Baghdad, the desert tribes and Qarmatian raiders grow ever bolder at its gates.",
      image: "images/places/mecca.png"  },
    { id: "kyiv",        name: "Kyiv",        region: "Rus'", x: 1120, y: 360, kind: "city",
      blurb: "Oleg's seat above the Dnieper. Rus' longships reach Miklagard; their pagan kings trade furs, wax and slaves for Byzantine gold.",
      image: "images/places/kyiv.png" },
    { id: "itil",        name: "Itil",        region: "Khazars", x: 1340, y: 400, kind: "city",
      blurb: "The capital of the Khazars at the Volga's mouth, a city of many gods and one ruler. Here we felt the stirrings of outer hunters, and Giovanni met an assassin from Alexandria praying in one of its churches.",
      image: "images/places/itil.png"  },
    { id: "talas",       name: "Talas",       region: "Türgesh", x: 1680, y: 500, kind: "ruin",
      blurb: "A generation ago, Abbasid and Tang armies met here and the world changed. Papermakers went west; something else went east. The battlefield still hums when lightning is near.",
      image: "images/places/talas.png" },
    { id: "taraz",       name: "Ṭarāz",       region: "Türgesh", x: 1660, y: 500, kind: "city",
      blurb: "A frontier oasis on the Talas river, where the settled lands meet the steppe. Not far from here, the armies of the Caliph and the Tang Emperor met and broke each other.",
      image: "images/places/taraz.png"  },
    { id: "turfan",      name: "Turfan",      region: "Uyghur", x: 1960, y: 530, kind: "city",
      blurb: "An oasis-kingdom of the Uyghurs, who follow the Buddha's path. Its cave-monasteries are painted with visions of paradise, a splash of color in the harsh desert.",
      image: "images/places/turfan.png"  },
    { id: "yarkand",     name: "Yarkand",     region: "Tarim Basin", x: 1780, y: 600, kind: "city",
      blurb: "An oasis on the southern Silk Road, a necessary stop for water and supplies. It lies in the shadow of the mountains, a small point of life in the vastness.",
      image: "images/places/yarkand.png"  },
    { id: "rome",        name: "Roma",        region: "Papal States", x: 870, y: 530, kind: "city",
      blurb: "A city of ghosts and ruins, where the Pope holds power amid the squabbles of Lombard and Frankish lords. It is a shadow of its former glory, but the center of the western faith.",
      image: "images/places/rome.png"  },
    { id: "venice",      name: "Venezia",     region: "Lombardy", x: 890, y: 490, kind: "city",
      blurb: "The lagoon-city, built on water and trade. It was here Giovanni was taken from his farm and made into what he is. The city bows to the Emperor in Constantinople but serves its own coin.",
      image: "images/places/venice.png"  },

    // Route-critical Silk Road cities (restored — referenced by the trade routes below)
    { id: "mosul",       name: "Mosul",       region: "al-Jazīra", x: 1220, y: 530, kind: "city",
      blurb: "A seat of emirs on the Tigris, where Mesopotamia meets the Anatolian hills. It is a city of trade and war, guarding the northern marches of the Caliphate.",
      image: "images/places/mosul.png"  },
    { id: "hamadan",     name: "Hamadān",     region: "Jibāl", x: 1280, y: 600, kind: "city",
      blurb: "The ancient capital of the Medes, now a firm seat of Buyid power beneath Mount Alvand. Its history is long, its merchants sharp, and its position vital.",
      image: "images/places/hamadan.png"  },
    { id: "balasagun",   name: "Balāsāghūn",  region: "Karluks", x: 1720, y: 480, kind: "city",
      blurb: "A city of the Karluk Turks, on the road to the Tian Shan mountains. It is a place of felt tents and earthen walls, a power rising on the steppe.",
      image: "images/places/balasagun.png"  },
    { id: "hami",        name: "Ḥāmī",        region: "Uyghur", x: 2020, y: 540, kind: "city",
      blurb: "A frontier oasis standing guard at the western end of the Hexi corridor. It is the last stop for caravans before they brave the greater deserts to the west.",
      image: "images/places/hami.png"  },
    { id: "luoyang",     name: "Luoyang",     region: "Tang", x: 2240, y: 630, kind: "city",
      blurb: "The eastern capital of the fading Tang dynasty. The city is weakened by court intrigue, but the great Buddhist carvings at Longmen still watch over the river.",
      image: "images/places/luoyang.png"  },
    { id: "herat",       name: "Herāt",       region: "Khorasan", x: 1470, y: 620, kind: "city",
      blurb: "A great city of Khorasan, a vital crossroads on the road between Nishapur and Balkh. To control Herat is to control an artery of the Silk Road.",
      image: "images/places/herat.png"  },
    { id: "kabul",       name: "Kābul",       region: "Kābul-Shāhī", x: 1540, y: 660, kind: "city",
      blurb: "The capital of the Hindu Shāhī kings, who bar the mountain passes from Khorasan. Their fortress holds the gate to the wealth of the Indus valley."  },
    { id: "basra",       name: "Basra",       region: "Iraq", x: 1290, y: 640, kind: "city",
      blurb: "The great Caliphate port where the rivers meet the Persian Gulf. From its docks, ships sail for India and beyond; in its schools, men debate the nature of God.",
      image: "images/places/basra.png"  },
    { id: "novgorod",    name: "Novgorod",    region: "Rus'", x: 1060, y: 260, kind: "city",
      blurb: "A frontier fort of the Rus', where the forest meets the river road. It is ruled by northmen, who trade in furs, slaves, and amber, and take tribute from the Slavic tribes.",
      image: "images/places/novgorod.png"  },
    { id: "medina",      name: "Madīnah",     region: "Ḥijāz", x: 1170, y: 750, kind: "city",
      blurb: "The Prophet's city, a place of pilgrimage and quiet governance. The descendants of the Prophet's house rule here in the Caliph's name.",
      image: "images/places/medina.png"  },

    // ══════════ Homelands of the party ══════════
    { id: "srinagar",    name: "Srinagar",    region: "Kashmir", x: 1660, y: 700, kind: "city",
      blurb: "Valley-city of lakes and houseboats, set among pines and peaks. Iksha Bhima — known to the caravans as Bansi — slipped out of her father's palace here, disguised as a servant boy, and never came back. Giovanni keeps ten followers in a chapel on the city's edge.",
      image: "images/places/srinagar.png" },
    { id: "saaremaa",    name: "Saaremaa",    region: "Eysysla (Baltic)", x: 640, y: 160, kind: "ruin",
      blurb: "An island in the Baltic, north-west of the Rus' rivers. Eskil's village stood here until the void opened at its center and swallowed it whole. He alone escaped — pulling himself from the surf while a strange fire ate the last of the houses.",
      image: "images/places/saaremaa.png" },
    { id: "taklamakan-home", name: "Taklamakan Tribe", region: "Uyghur steppe", x: 1860, y: 550, kind: "tribal",
      blurb: "Turkic Uyghur encampment in the desert of death. Lüèduó grew up dancing their histories around the fires — until a Chinese lord, tired of raids, rode in with an army and demanded hostages. Lüèduó was handed over.",
      image: "images/places/taklamakan-home.png" },

    // Fantastical edge markers
    // ══════════ Campaign sites (Book 1 + session notes) ══════════
    { id: "saint-severus", name: "Monastery of Saint Severus", region: "Apennines (Lombardy)", x: 880, y: 515, kind: "ruin",
      blurb: "In a high Apennine monastery, we found Brother Aldric's sealed crypt. By liturgy, he had thinned the world's skin; Father Matthias's hands passed through stone, while Father Clement was undone by the floor's geometry. Giovanni alone escaped that place — the hidden engine of his whole story.",
      image: "images/places/saint-severus.png" },
    { id: "aquileia", name: "Aquileia", region: "Adriatic, Friuli", x: 894, y: 476, kind: "city",
      blurb: "The seat of the Patriarch Ursus, a key frontier city of the Lombards. It was from here that Giovanni first fled east, and here we later gained our standing after burning the corruption from San Floriano.",
      image: "images/places/aquileia.png" },
    { id: "ravenna", name: "Ravenna", region: "Romagna", x: 890, y: 510, kind: "city",
      blurb: "Once the seat of western emperors, now of the diabolist Bishop Carol. In his palace of mosaics, we refused his offer to master the Outer Beings and fought our way past his creatures. We left his halls to the flames.",
      image: "images/places/ravenna.png" },
    { id: "bari", name: "Bari", region: "Apulia (Byzantine themes)", x: 910, y: 540, kind: "city",
      blurb: "We found refuge in this Byzantine port, capital of their Italian themes. In a governor's villa, we healed our wounds under the eye of Bishop Andronicos. On its beaches, Brianna learned the arts of Vengeance.",
      image: "images/places/bari.png" },
    { id: "montegranaro", name: "Montegranaro", region: "Duchy of Spoleto", x: 890, y: 525, kind: "ruin",
      blurb: "A Lombard fortress-town clinging to its granary mountain. Here we found our contact Blanca transformed into a many-limbed horror. We purged the mutated village and its barred church with fire, leaving only ash.",
      image: "images/places/montegranaro.png" },
    { id: "san-floriano", name: "San Floriano", region: "Slavic Marches (NE of Aquileia)", x: 920, y: 448, kind: "ruin",
      blurb: "In the Slavic Marches, a land of new faith and old gods, we found an abbey fallen to a harvest cult. In the Gorska-Stvar cave above, we banished a messenger of Shub-Niggurath. We cleansed the abbey below it in a great Battle Mass, leaving it a smoking ruin.",
      image: "images/places/san-floriano.png" },
    { id: "sophia-tower", name: "Sophia's Island Tower", region: "Aegean Sea", x: 1010, y: 510, kind: "ruin",
      blurb: "On an island in the Aegean, where hermits and scholars hide from the world, stood the Hermetic Order's tower. There we trapped a Hound from the angles of time within an iron sphere. We burned the creature alive, and its tower burned with it.",
      image: "images/places/sophia-tower.png" },
    { id: "susa", name: "Sūsa", region: "Ifrīqiya (near Carthage)", x: 864, y: 605, kind: "city",
      blurb: "A fortified port of the Aghlabid emirs, its harbor crowded with corsairs and slave-ships. In the emir's palace, Sofia told us our curse could not be broken. Here too we saw Tabiri again, reborn as the pirate-queen Hennataui.",
      image: "images/places/susa.png" },
    { id: "shrine-of-storms", name: "Shrine of Storms", region: "Saharan deep desert", x: 920, y: 720, kind: "ruin",
      blurb: "In the deep desert stand tombs older than the Pharaohs. We sought one such place, a cliff-shrine to an Atlantean queen, past wards and guardians of inhuman shape. From her sarcophagus we took the storm-tiara that could banish the Feaster from Afar.",
      image: "images/places/shrine-of-storms.png" },
    { id: "tyre", name: "Tyre", region: "Phoenician coast", x: 1140, y: 600, kind: "city",
      blurb: "An island-port of corsairs, straddling the Caliphate and the Sea. Below the fighting pits we found caverns of an older faith and slew the fish-demon child of Dagon. We left Lod buried in the collapse.",
      image: "images/places/tyre.png" },
    { id: "aidhab", name: "Aidhab", region: "Red Sea (Sudanese coast)", x: 1170, y: 830, kind: "city",
      blurb: "The Red Sea port where pilgrims and merchants cross to Arabia. Here we landed on Soleman's ships and saw the Emperor's agent Fashian put his hooks into Lüèduó. It was in Aidhab that we hired Tabiri of Shendi as our guide into the desert.",
      image: "images/places/aidhab.png" },
    { id: "ikhmindi", name: "Ikhmindi & the Khem-Sethi Temple", region: "Nubia, west bank Nile", x: 1090, y: 830, kind: "ruin",
      blurb: "A fortified town of the Nubian Christians, near the great cataracts. Beneath it lay a temple older than Egypt, where Akivasha slept in crystal and the Feaster from Afar was chained. Isaac perished there, but we fled with the Book of Eibon.",
      image: "images/places/ikhmindi.png" },
    { id: "iram", name: "Iram, the City of Pillars", region: "Crimson Desert (Rub' al-Khālī)", x: 1300, y: 870, kind: "ruin",
      blurb: "A buried city of pillars, spoken of by desert-prophets, that we could not see until an incantation was spoken. At its heart, Bansi took Akivasha's head from her shoulders in a burning throne-room. But our misuse of the Book released another, unnamed thing into the world.",
      image: "images/places/iram.png" },
    { id: "hind-fortress", name: "Hind's Desert Fortress", region: "Yemen interior", x: 1230, y: 870, kind: "ruin",
      blurb: "Inland Yemen is a land of stone fortresses, built to guard against raids. In one such place, the caravan-queen Hind gave us shelter, only for her court to be slaughtered by assassins. We left her humbled in her bloody halls and rode on.",
      image: "images/places/hind-fortress.png" },
    { id: "multan", name: "Multan", region: "Sindh / Punjab", x: 1620, y: 740, kind: "city",
      blurb: "The great city of the Sun Temple, a wealthy pilgrimage site on the Indus. Here Bansi spent two years with a guild of thieves and healers. They taught her to read locks as a language and gave her the lye-burned tattoo she bears.",
      image: "images/places/multan.png" },
    { id: "quilon", name: "Quilon", region: "Malabar coast", x: 1700, y: 970, kind: "city",
      blurb: "A great port of the Malabar coast, where merchants of all faiths trade their wares. In an unmarked shrine to Kali, an old tantrika stripped every name and face from Bansi, who died and was reborn. The scars on her hands and the cold mark on her brow are from that place.",
      image: "images/places/quilon.png" },
    { id: "hormuz", name: "Hormuz", region: "Persian Gulf", x: 1330, y: 720, kind: "city",
      blurb: "A mainland port at the mouth of the Gulf, trafficking in pearls, spices, and men. Here Bansi slew two slavers and burned their bone debt-chits. She sailed south from this place on a Yemeni dhow, having bought a man his freedom with blood.",
      image: "images/places/hormuz.png" },
    { id: "ujjain", name: "Ujjain", region: "Mālwa (Pratīhāra)", x: 1660, y: 860, kind: "city",
      blurb: "An ancient city of learning, the prime meridian of Indian astronomers. We rested here between trials, and Eskil found rare metals and a perfect sapphire for his work. Giovanni, for his part, had a simple stone cross carved in a mason's yard.",
      image: "images/places/ujjain.png" },
    { id: "jayashri-palace", name: "Jayashri's Enchanted Palace", region: "Rāṣṭrakūṭa lands (north of Ellora)", x: 1640, y: 890, kind: "ruin",
      blurb: "North of Ellora, where kings carve temples from living rock, we found a cursed palace of a serpent-blooded line. Its people were turned to stone, its princess suspended in living crystal. We freed her, and she gave us the mantra to pass into the serpent-realm of Nagaloka.",
      image: "images/places/jayashri-palace.png" },
    { id: "satyavati-shrine", name: "Satyavati's Mountain Shrine", region: "South India (Karnataka jungle)", x: 1680, y: 925, kind: "tribal",
      blurb: "High in the jungle mountains, past lizard-men and a demon-lord's watch, we sought a Kali-shrine. There, a mystic of the skull-bearing Kapalika sect cured Sadia of her wolf-curse. The price was the storm-tiara we had taken from the desert.",
      image: "images/places/satyavati-shrine.png" },
    { id: "iron-gates", name: "The Iron Gates (cursed castle)", region: "3 days east of Samarkand", x: 1620, y: 550, kind: "ruin",
      blurb: "East of Samarkand, beyond the strategic pass they call the Iron Gates, stands a ruined keep. Its village choked its own well with corpses, and ghouls climbed the walls at dusk. Beneath, in a chamber of alien statues, we were betrayed.",
      image: "images/places/iron-gates.png" },
    { id: "merv-kurgan", name: "The Kurgan above Merv", region: "Steppe east of Merv", x: 1480, y: 510, kind: "ruin",
      blurb: "The steppe is dotted with ancient burial mounds, which the Turks see as doors to other worlds. Above Merv, we found one ringed with flayed skins, its peak a portal to a hidden library. Beneath it lay the grave of a warrior-king, awaiting a dark summons.",
      image: "images/places/merv-kurgan.png" },
    { id: "cathedral-of-bones", name: "The Cathedral of Bones (Nightwolf Stronghold)", region: "Forest north of Itil", x: 1300, y: 240, kind: "ruin",
      blurb: "Deep in the northern forests, we found the Nightwolf's stronghold, a fortress of mortared bone and skull-palisades. In the cathedral of ribs and pelvises, we faced Karishkir and his court. We beheaded the sorcerer and left his throne of bones to the fire.",
      image: "images/places/cathedral-of-bones.png" },
    { id: "serpents-rest", name: "The Serpent's Rest", region: "Deep Taklamakan", x: 1900, y: 600, kind: "ruin",
      blurb: "The desert of death hides cities swallowed by sand. One such place, of pre-human design, called to the serpent in Lüèduó's blood. Beneath its impossible architecture, the Nagini claimed him and set her mark upon his wrist.",
      image: "images/places/serpents-rest.png" },
    { id: "penjikent", name: "Penjikent", region: "Sogdian foothills", x: 1525, y: 560, kind: "city",
      blurb: "In the Sogdian foothills stand the painted ruins of Penjikent, a memory of a great merchant-kingdom. In a village nearby, Lüèduó found the giant Eskil at a forge, mending a plow. They took each other's measure and rode for Samarkand at dawn.",
      image: "images/places/penjikent.png" },
    { id: "gol-goroth-pillar", name: "The Pillar of Gol-Goroth", region: "Taklamakan north of Gooma", x: 1800, y: 590, kind: "ruin",
      blurb: "Among the ruins of an old Tibetan fort, half-buried in the dunes, stands a great stone pillar. A toad-thing of a thousand mouths sat atop it, which we slew and bound into the Book. At the pillar's base, we found four chests of Atlantean make.",
      image: "images/places/gol-goroth-pillar.png" },
    { id: "issyk-kul", name: "Issyk Kul (Khan's Ordu)", region: "Tian Shan steppe", x: 1750, y: 440, kind: "tribal",
      blurb: "By the shores of the high, wind-haunted lake called Issyk Kul, the Khan of the Nine Skulls gathered his tribe. It was here we first saw him, armored in some unholy metal. The blades of assassins had no effect upon him.",
      image: "images/places/issyk-kul.png" },

  ],

  routes: [
    { id: "silk-principal", name: "Principal Silk Road", color: "crimson", bold: true,
      points: ["baghdad","mosul","hamadan","rey","nishapur","merv","bukhara","samarkand","taraz","balasagun","turfan","hami","dunhuang","luoyang","changan"] },
    { id: "silk-south", name: "Southern Road", color: "gold",
      points: ["baghdad","nishapur","herat","balkh","kabul","kashgar","yarkand","khotan","dunhuang"] },
    { id: "sea-route", name: "Indian Ocean Route", color: "teal",
      points: ["basra","aden","quilon"] },
    { id: "varangian", name: "Varangian Way", color: "violet",
      points: ["novgorod","kyiv","constantinople","baghdad"] },
    { id: "incense",   name: "Incense Road", color: "gold",
      points: ["mecca","medina","aden"] },
  ],

  journey: [
    // Book 1 (Episodes I–VII): party converges at Samarkand and rides west.
    "samarkand", "iron-gates", "merv", "merv-kurgan", "merv",
    "shiraz", "cairo", "aidhab", "ikhmindi", "constantinople",
    "itil", "cathedral-of-bones",
    // Continuation (Episodes 8–23): the wider arc through Italy, Africa,
    // Yemen, India, Kashmir, the steppe, and back to Samarkand.
    "montegranaro", "bari", "ravenna", "constantinople", "aquileia",
    "san-floriano", "susa", "shrine-of-storms", "tyre", "aden",
    "iram", "quilon", "satyavati-shrine", "jayashri-palace", "srinagar",
    "talas", "taklamakan-home", "khotan", "gol-goroth-pillar", "issyk-kul",
    "samarkand",
  ],

  characters: [
    {
      id: "giovanni",
      name: "Giovanni di Venezia",
      role: "Priest-assassin; envoy of the Church",
      origin: "Venice",
      languages: ["Vulgar Latin", "Latin", "Greek", "Hebrew", "Literary Arabic"],
      arcCareers: ["Farmer", "Merchant", "Priest", "Assassin"],
      hook: "A priest-assassin who only kills when he can call it justice — and who is learning, on the road east, how thin that word has worn.",
      appearance: "Olive-skinned, lean, calloused at the hands long after the plow; a white scar at the ribs from a Patriarch's bodyguard in Aquileia. He carries a worn merchant's dagger, a crucifix at his throat, and a quarterstaff. People notice first the stillness — the posture of a man who has already decided where the exits are, dressed in robes whose vocation should have made such calculations unnecessary. Then they notice the voice, trained equally for haggling, homiletics, and the moment before a kill.",
      background: "Sent as the junior member of a curial inquiry to the Monastery of Saint Severus in the Apennines, Giovanni watched Brother Aldric's heretical liturgy thin a stone door into something that was not stone, and watched what came through it take Father Matthias's face and Father Clement's mind. He carried the scholar Clement out alive and dying both, and came down out of the mountains a smaller and colder believer than he had gone up. Years later in Venice, Bishop Paulus put that wound to use — turned the country boy who had once told a merchant he was cheating his father into the Church's quiet blade, until a frame-up at the Patriarch of Aquileia opened him along the ribs and sent him fleeing east, with a knife always one bathhouse behind him.",
      partyRole: "The company's confessor, its inspirer in battle, and — when the work demands it — its quietest killer. He has the merchant's eye for a lie and the assassin's eye for a throat, and uses both. With Bansi, he begins as the priest who catches her stealing from Hind's coffers and refuses to report her. With Eskil, he is brother-keeper, the voice that hauls the Norseman back from Akivasha's pool. With Lüèduó, he is the Catholic priest learning to ride beside something serpent-blooded and other, and choosing — episode by episode — to keep riding. None of the four trust easily. Giovanni is often the one who insists they try.",
      theme: "The rationalization of violence under the cover of righteousness — and the slow erosion of that cover by what the Silk Road is teaching him about the shape of the cosmos. Every kill east of Venice has needed less doctrine and more honesty to justify. The cursed runesword that passes to him at the end of Episode VII is not a weapon. It is penance — a leash he asks to wear because no one else can be trusted with it.",
      stats: { str: 1, agi: 2, mind: 2, appeal: 2, melee: 2, ranged: 1, defense: 0, initiative: 3, lifeblood: 11, hero: 4 },
      signatureItems: [
        "Corrupt runesword (d6H) — taken up as penance in Ep. VII",
        "Bishop Karol's signet ring",
        "Elaborate silver crucifix; Bible",
        "Quarterstaff, sling; merchant's dagger",
        "Masterwork vestments (reroll first 1)",
      ],
      abilities: ["Ius Dei", "Psalm-Singer's Sorrow", "Silver Tongue", "Sneaky", "Inspire", "Fearless", "Battle Harness"],
      followers: [
        "Fr. Renigius + 10 rabble — Roman church, Constantinople",
        "10 rabble — chapel at Srinagar",
      ],
      placeIds: ["venice", "constantinople", "srinagar", "baghdad", "samarkand"],
      portraits: [
        { src: "images/portraits/giovanni-road.png", caption: "On the road to Samarkand" },
        { src: "images/portraits/giovanni-praying.png", caption: "Kneeling alone in a Western-rite church" },
      ],
      quote: { text: "That is not a plan. That is penance.", source: "Chapter Nineteen, The Cathedral of Bones" },
    },

    {
      id: "eskil",
      name: "Eskil of Eysýsla",
      role: "Varangian rune-warrior, Guild Executioner",
      origin: "Saaremaa (Eysýsla), the Baltic",
      languages: ["Arabic", "Slavic", "Old Norse"],
      arcCareers: ["Blacksmith", "Gladiator", "Executioner", "Runesmith (Magician)", "Stygian Scholar"],
      hook: "A Norseman locked into his own armor so he cannot eat himself, walking south because the thing that wants him is still walking north.",
      appearance: "Six feet eight, two hundred and eighty pounds of scarred muscle under shaggy black hair and pale blue eyes. A steel collar is fused at his throat and a many-holed helm caged to it; the seams were welded with molten iron and have not opened since. When he can afford the materials he stains his skin red with henna and draws layered protections across his flesh — Norse warding runes from his brother Leif, elder signs from forbidden books, inverted sigils of the Black Goat. At his belt hangs an iron skull that whispers in a dead man's voice.",
      background: "In the Undercroft beneath Saaremaa, the priestesses of Shub-Niggurath fed their Messenger five nights a week. Eskil was the chosen meat — drugged, bedded, and almost torn apart, his blood already half-prepared as a vessel for the concentrated vigor of his entire people. At the last instant he scratched a rune Leif had taught him, and his brother died in his place; the village burned under a purple wound in the sky and the compact of Eysýsla collapsed. What survived was Eskil, his blood now ambrosia to anything from beyond the veil, the hunger to consume himself riding inside him forever, and a fragment of Leif sealed in iron to keep him company. He fled down the Dnieper, was enslaved in Kyiv, fought as a gladiator, was freed by a Guild Executioner who recognized promise in his frame, and took the headsman's cloak for his lifestyle: transient, legal, alone.",
      partyRole: "The heaviest hand and the closest to the cosmic — the one the others put at the back when they walk into the dark, the one they shout at when something has its hooks in him. He stands in the line beside Bansi, lends his strength to her cleverness, and treats her with the wary respect of one survivor for another. Lüèduó he reads as kin: another man with something coiled inside that is not him. With Giovanni the bond is closest and strangest — they save each other repeatedly from compulsion, the priest's voice the one that can crack through when nothing else will.",
      theme: "The man who can stand in front of horror because horror has already eaten part of him. Proof that the cosmic does not always kill on first contact — sometimes it marks, and the marked walk on, and their walking becomes shelter for everyone behind them. The cost is that he can never be a man among men again: he sleeps apart, eats alone, locks his own mouth shut, and lets the brother in the iron skull keep him sane.",
      stats: { str: 5, agi: 2, mind: 2, appeal: 0, melee: 3, ranged: 1, defense: 3, initiative: 1, lifeblood: 15, hero: 5, arcane: 17 },
      signatureItems: [
        "Warblade — Furore Normanum (Mythic, d6H×2). Inscribed: \"A furore Normannorum libera nos, Domine.\"",
        "Silver helm locked into iron collar (cannot be removed)",
        "Leif's iron skull — chained to belt, whispers in a dead man's voice",
        "Malum, MW Evil Bladed Buckler",
        "Masterwork piecemeal medium armor (d6-2 protection)",
        "Smith's kit with rope, pitons, lantern, bedroll",
      ],
      abilities: ["Giant Strength", "Born Athlete", "Feat of Strength", "Power of the Void"],
      flaws: ["Distinctive Appearance — Unremovable Helm", "Fear of Vertexes — human architecture (see Hounds of Tindalos)", "Morgazzon's Curse — speaks to dead brother Leif"],
      followers: [],
      placeIds: ["saaremaa", "kyiv", "constantinople", "samarkand"],
      portraits: [
        { src: "images/portraits/eskil-sackcloth.png", caption: "Sackcloth over the runes, entering a city" },
        { src: "images/portraits/eskil-ritual.png", caption: "Blood on the sigil, the hand that pays" },
        { src: "images/portraits/eskil-market.png", caption: "The rain market — revealed" },
      ],
      quote: { text: "I am a jailer. And also a prisoner.", source: "Chapter Fourteen, The Weight of What Was Done" },
    },

    {
      id: "lueduo",
      name: "Lüèduó",
      role: "Uyghur dancer-spy, Naga-touched agent",
      origin: "Turkic Uyghurs of the Taklamakan Desert",
      languages: ["Arabic", "Uyghur", "Chinese", "Agentcraft", "Sanskrit"],
      arcCareers: ["Dancer", "Lothario", "Agent", "Merchant", "Naga"],
      hook: "A Uyghur dancer-spy whose every grace is borrowed, and the lender keeps a ledger.",
      appearance: "Called Raven — a name granted by an Emperor for the black of his hair and the way he moved beneath it. Born Quzghun among the horse-clans at the edge of the Taklamakan. High cheekbones, a mouth that curved cruel and kind by turns, hair black as a wet bough falling straight to his shoulders. His eyes are the tell: golden-amber, and in certain lights the pupils narrow to vertical slits and refuse to round again. Beneath sleeves and collar, a faint iridescence rides his skin where the scales are learning his shape.",
      background: "Something old was already curled in his blood when he was born — a diluted line of the Nagini's ancient servants, dormant for generations until the shamans of his clan saw the door behind his eyes and refused to teach him to open it. Sent east as a hostage, he danced his way from war-prize to imperial favorite to spy in the bed-chambers of the court, harvesting secrets for the eunuch spymaster Wei. An affair with Lady Mei, the wife of a councillor too powerful to cuckold, ended with her dragged to her death and Lüèduó banished west on a 'die usefully if you can' assignment that delivered him to a buried temple called the Serpent's Rest. The Nagini was waiting. She had always been waiting. She bit him, claimed him, and opened the debt that he has been paying ever since.",
      partyRole: "The party's mouth and its eavesdropper. He speaks every tongue the Silk Road sells and reads a room's loyalties in thirty seconds, a habit Wei drilled into him before the curse made it instinct. He is the one who finds Eskil at the smithy in Penjikent and recognizes a fellow cursed soul; the one who first marks Nizack as false near the Iron Gates; the one who reaches Giovanni's bleeding throat in Shiraz and refuses to let him die in the street. With Bansi he runs a thieves' shorthand of glances and unspoken contracts. With Eskil he keeps a wary brotherhood of two damned men who do not need to discuss the damnation. With Giovanni he discovers, slowly and with reluctance, that he is capable of loyalty that is not also leverage.",
      theme: "The novel's accountant of debt. Every supernatural transaction in his life carries a running balance. She tallies. He can feel her tallying. Where Eskil bears his curse as a weight to be resisted and Giovanni bears his sins as a penance to be carried, Lüèduó bears his as a debt to be serviced, indefinitely, with interest. The compulsion that emptied his purse at the caravanserai is the same compulsion that opens the door for the Nagini each time she knocks. He knows it. He plays anyway.",
      stats: { str: 0, agi: 2, mind: 4, appeal: 2, melee: 2, ranged: 1, defense: 1, initiative: 1, lifeblood: 10, hero: 4, arcane: 10 },
      signatureItems: [
        "Adder's Aegis — Mythic scale armor with integrated cobra-hood helm. A purple gem in the chest contains Kizile Krum, frozen in an eternal scream.",
        "Pear crystal in \"Crown Royale\" bag",
        "Agent's tools: chalk, wax, key, mirror",
        "Sketchbook",
        "Dagger (d6L); bow; spear (20')",
      ],
      abilities: ["Attractive", "Detect Deception", "Beguiling", "Familiar Power (Nagini)", "Rebound Magic", "Magic Sink / Counter", "Hypnotize", "See Others", "Enter Spirit Realm"],
      flaws: ["Cravings — gambling with and for gems", "Hunted — agents of the Chinese emperor", "Distinguishing Features — ovular pupils, hint of scales"],
      followers: ["Yas the Knife + 10 rabble (periodic)"],
      placeIds: ["taklamakan-home", "changan", "samarkand", "merv", "constantinople"],
      portraits: [
        { src: "images/portraits/lueduo-scholar.png", caption: "The Tang court scholar, composed" },
        { src: "images/portraits/lueduo-dancer.png", caption: "Dancing; the Nagini close to the surface" },
        { src: "images/portraits/lueduo-fangs.png", caption: "Fangs bared, eyes gold" },
        { src: "images/portraits/lueduo-dog-attack.png", caption: "Night in the Naiman camp, with Gan" },
      ],
      quote: { text: "I am a dancer. A spy. A gambler who cannot resist the call of the dice. I am a man who carries something in his blood that is older than the empires we travel through.", source: "Episode I, Chapter Two — The Iron Gates" },
    },

    {
      id: "bansi",
      name: "Bansi (Iksha Bhima)",
      role: "Noble-born thief, sailor, devotee of Kali",
      origin: "Srinagar, Kashmir",
      languages: ["Arabic", "Sanskrit", "Bengali", "Dogri", "Thieves' Cant"],
      arcCareers: ["Noble", "Poet", "Thief", "Sailor (Sea Rogue)", "Scholar"],
      hook: "A princess who picked her own locks, a thief who picked Kali's, and the youngest blade in a company that mostly forgets she is the most dangerous person in the room.",
      appearance: "Small, fast, deceptively unobtrusive — the build of someone who moves through crowds without disturbing them. Her hands are her most legible feature: princess's bones under hundreds of fresh, fine scars left when Kali 'cut out what did not belong,' so profuse the skin has changed color. Between her brows, a cold spot the tantrika's thumb pressed into her — Kali's mark, invisible and always present. A sickle slung across her back as a 'tool,' a brace of fine balanced daggers beneath, a wooden flute her mother gave her, and a length of razor-wire disguised as jewelry.",
      background: "Iksha was a chess piece her family forgot to play until the price was right — promised at thirteen as sixth wife to a fifty-three-year-old Shahi. Overhearing her own bride-price quoted in her uncle's voice, she walked out of the palace dressed as a servant boy, took her name from a flute, and fell in with a westbound caravan. In Multan the Bahn-Sa-Sahn — a thieves' guild — taught her locks under Dalir, who moved like a dancer, and broke her on the mat under Arjun until she learned that survival was a craft, not a gift. Two years later, after a job in Hormuz that ended a slaver ring and put her on a Yemeni dhow, the storm took her friend Tarek and showed her what waited under the water. At Quilon she was drawn to a shrine she had not been seeking, and an old tantrika put her on the floor of Kali's awareness and said: you belong to time, and time belongs to her.",
      partyRole: "The company's eyes, hands, and lockpick — the one sent up the wall, into the upper embrasure, alone to the wharf-side guild. She runs point with Giovanni in every dungeon from Ikhmindi to the Night Wolves' keep; she trades information with Lüèduó in low voices over a whetstone and tells no one else; she covers Eskil's flank when his curse pulls him toward something he cannot resist, and slaps him hard enough across the helm to bring him back. She is the youngest of the four and the most professionally trained in violence.",
      theme: "What survival looks like when you decline to become anyone's instrument. Every authority that has tried to own her — palace, guild, slaver, queen, even the goddess — has gotten skill back instead of obedience. Her great motif is the lock: every lock is a language, and she would rather understand a thing than break it. Kali's claiming is the one debt she did not pick herself and cannot pick open; kala is time, and time always comes due.",
      stats: { str: 1, agi: 3, mind: 2, appeal: 2, melee: 2, ranged: 3, defense: 2, initiative: 1, lifeblood: 12 },
      signatureItems: [
        "Legendary Inscribed Scimitar (2d6H) — Sanskrit: \"Strike fear into the hearts of demons and rakshasas.\"",
        "Four balanced daggers (2d6L, reroll 1's)",
        "Iron Silk battle-harness — Fero Seraum, medium armor hidden under clothing",
        "Bansuri flute — given by her mother",
        "Amulet Luca made; Evil Girdle of Doom; loot from Nagini",
        "Thieves' tools; disguises; desert tents, camels, Chinese desert clothing",
      ],
      abilities: ["Master of Disguise", "Sneaky", "Wake-up (Lifepoints +1/day)", "Sea Rogue combat bonus (inc. sea monsters)"],
      flaws: ["City Dweller (bought off)"],
      followers: ["Affiliated with Bahn-Sa-Sahn thieves' guild"],
      family: "Father: Kanishka, Raja of Sonapura. Mother: Maya. Brother: Vikrahma.",
      placeIds: ["srinagar", "multan", "samarkand", "constantinople"],
      portraits: [
        { src: "images/portraits/bansi-alley.png", caption: "Twin daggers, torchlit alley" },
        { src: "images/portraits/bansi-climb.png", caption: "Over the wall, disguised as a servant boy" },
      ],
      quote: { text: "I think you are the demon this scimitar was meant to kill.", source: "Episode VII: The Night Wolves, to Karishkir, mid-charge" },
    },

    {
      id: "gan",
      name: "Gan, the bold one",
      role: "Naiman beastmaster-shaman, last of their tribe",
      origin: "Naiman Mongolian tribe of the Altai Mountains",
      languages: ["Arabic", "Altai", "Mongolic"],
      arcCareers: ["Beastmaster", "Hunter", "Healer"],
      hook: "A foundling raised in the stables, the last of a tribe no one remembers, who speaks to a golden eagle and a bankhar dog in a language that was never written down.",
      appearance: "Short-haired, weathered, compact. Fur-trimmed leather armor layered for cold steppe nights; a longbow with the arm-curve of a horse-archer, and a full quiver at the hip. They move with the quiet economy of someone who has spent more hours among animals than people, and whose companions have taught them that sudden motion is a way to lose a friend.",
      background: "A foundling, left in the stables of a Naiman camp in the high Altai. They grew up among the animals who accepted them first, and learned healing from the camp's shaman before the shaman died. The tribe fell — to plague, to raid, to something else — and Gan walked south alone with a golden eagle on one arm and a bankhar dog at their heel.",
      partyRole: "The quiet one at the edge of the fire. Rarely speaks and listens carefully when they do. Their eagle and their dog see what the others miss; their hands have set more bones than they have broken. Encountered the party near the Naiman camp on a night a yellow-eyed stranger tried to enter it, and stayed.",
      theme: "Last-survivorship as vocation. Where Eskil's survival made him a weapon and Lüèduó's made him an asset, Gan's made them a keeper — of animals, of stories, of wounds that belong to other people. The shamanism is quiet; the bow is not.",
      stats: { str: 1, agi: 1, mind: 2, appeal: 1, melee: 1, ranged: 2, defense: 1, initiative: 1, lifeblood: 10, hero: 5 },
      signatureItems: [
        "Sword (d6); staff-sling (d6L); bow (d6)",
        "Light leather / animal-hide armor (d6-3)",
        "Shaman's kit — healing herbs, bones, fetishes",
      ],
      abilities: ["Beast-Friend", "Mighty Shot"],
      flaws: ["Absent-Minded"],
      companions: ["Golden eagle", "Bankhar (Mongolian mastiff) dog"],
      followers: [],
      placeIds: ["altai-home", "samarkand"],
      portraits: [
        { src: "images/portraits/gan-dog-attack.png", caption: "Night in the Naiman camp — with Lüèduó" },
      ],
      quote: null,
    },
  ],

  npcs: [
    { id: "vizier", name: "The Veiled Vizier", role: "Patron, Baghdad",
      blurb: "Sent the party east to retrieve a manuscript. Every letter he sends has been opened before it reached us. We have never seen his face." },
    { id: "kumiss", name: "Old Kumiss-Mother", role: "Ghuzz horse-witch, the steppe",
      blurb: "Met north of Merv. Traded us directions for a song. Her mare is older than any living Turk and answers to no rein." },
    { id: "hongbian", name: "Hongbian 洪辯", role: "Librarian-monk, Dunhuang",
      blurb: "Keeper of the sealed cave. Claims to have met us before, in a life we do not remember." },
    { id: "jade-merchant", name: "The Jade Merchant of Khotan", role: "Broker",
      blurb: "Never gives a name. Will buy anything with writing on it, for silver or for favors that come due later." },
  ],

  villains: [
    { id: "karishkir", name: "Karishkir", faction: "Kveld-Ulf",
      image: "images/villains/karishkir.png",
      blurb: "Werewolf-queen, three centuries old, lover of three — Nizack the sorcerer, Drekhlo the dragon-claw, and Revna the Nightwolf Huntress — and voice of compulsion across the steppe. She wakes among them in a temple of skulls and reaches into our minds with visions tailored to break us. Bansi's scimitar-pommel stunned her; Eskil took her head; Bansi flung the still-aware skull off the terrace into the void. The cathedral burned. Her cursed sword still speaks." },
    { id: "drekhlo", name: "Drekhlo", faction: "Kveld-Ulf",
      image: "images/villains/drekhlo.png",
      blurb: "Dragon-claw, Karishkir's first lover, marked Eskil at Merv and swore he would drink his blood from his empty skull. At the Cathedral of Bones he came near to it — his greatsword punched through Eskil's spine. Rahzalahn's thrown blade consumed him as he charged. The greatsword could not be destroyed by hammer or fire; it whispers still, sheathed across Giovanni's back as penance." },
    { id: "revna", name: "Revna the Nightwolf Huntress", faction: "Kveld-Ulf",
      image: "images/villains/revna.png",
      blurb: "Karishkir's third, bearer of the Kveld-Ulf — the Nightwolf dagger. We took her arms with Bansi's scorpion-venom from the gallery, and Bansi somersaulted off it to take her head. Eskil shattered her dagger with his war-blade. We will not forget the sound it made." },
    { id: "akivasha", name: "Akivasha", faction: "Stygian remnant",
      image: "images/villains/akivasha.png",
      blurb: "Priestess-queen of an order older than the pyramids, woken in the Khem-Sethi temple beneath Ikhmindi when our amulet locked into her crystal sarcophagus. She tried to draw Eskil into her pool by his cursed blood, and laughed at our retreat: \"You cannot undo what has been done. You cannot seal what has been opened.\" She is whole now, walking the chasm where we fled. The largest debt we have left unpaid." },
    { id: "nizack", name: "Nizack", faction: "Kveld-Ulf",
      image: "images/villains/nizack.png",
      blurb: "The first of Karishkir's three lovers — sorcerer, gate-opener, hired by Hind in Samarkand under a smile, contracted to retrieve a cursed amulet from a ruined keep beyond the Iron Gates. He betrayed us at the buried-chamber altar; Eskil took his hand and it turned to smoke; he opened a shadow-door and was gone. We met him again at the Chapel of Bones beneath Merv, where Rahzalahn's silver hair-comb went into his throat from behind and three silver daggers into his heart. He disintegrated. Some debts close cleanly." },
    { id: "khan-nine-skulls", name: "The Khan of the Nine Skulls", faction: "Steppe; raised dead",
      image: "images/villains/khan-nine-skulls.png",
      blurb: "A warlord raised by Karishkir from his kurgan; he sits at her fire casting only one shadow. Gan brought us the news from a one-eyed steppe-shaman beyond Shiraz. He gathered at Itil with the cult's coalition before the cathedral; he was not in the cathedral when it fell. He is somewhere else now. His banner has been seen from the Volga to the Yellow River in the same season." },
    { id: "vampires-shiraz", name: "Paul and the Sister", faction: "Vampire family",
      image: "images/villains/vampires-shiraz.png",
      blurb: "Giovanni \"freed\" a slave he renamed Paul, mistaking a predator for a soul reborn. Paul led us to the silent house of the antiquarian Kerdir in Shiraz, where his \"sister\" opened Giovanni's throat in one swipe. Both fled as whirlwinds of dust. The sister appeared again in Constantinople wearing the face of \"Helena,\" sister to a man called Michael — they came nearer to taking us a second time, and went again into the night." },
    { id: "feaster", name: "The Feaster from Afar", faction: "Cosmic horror",
      image: "images/villains/feaster_v2_1.png",
      blurb: "Released by Abu-Rayhan's possessed chant beneath Ikhmindi when the Khem-Sethi summoning took his tongue. A hollow talon drove through Isaac's temple and drank his mind; we saw it for an instant before we ran. The witchfire pulse it left under the temple has not stopped. We do not know what it eats now that we have left." },
    { id: "bishop-paulus", name: "Bishop Paulus of Venice", faction: "The Church (Venice)",
      image: "images/villains/bishop-paulus.png",
      blurb: "The man who saw Giovanni's wound from Saint Severus and put it to use, made him a blade, sent him east to clean the Church's quietest accounts. The cursed greatsword speaks in his voice now, tempting Giovanni home to finish what was started. The Bishop of Ravenna's letters — and the Alexandrian assassin who carried them — are likely his hand reaching after us." },
    { id: "wei", name: "Wei, Majordomo of the Tang", faction: "Tang court",
      image: "images/villains/wei.png",
      blurb: "The eunuch spymaster who recited Lüèduó's entire ledger of seductions back to him in a bare lamplit chamber and recruited him on the spot. Touched his shoulder once and told him to make it count. The Imperial bounty now riding the Volga at Lüèduó's heels came from Wei's ministry; Fashian, the agent who blackmailed us at Aidhab, answers to him. Lüèduó's leash is older than his curse." },
  ],

  items: [
    { id: "furore-normanum", name: "Furore Normanum", kind: "Mythic war-blade",
      blurb: "Eskil forged his great war-blade in the arenas of Kyiv, and with it bound the life of the sorcerer Jadu-gar into a sapphire set in its hilt. The Latins pray 'From the fury of the Northmen, deliver us,' but Eskil turned their litany back upon them, inscribing it on the steel that will free the sorcerer's soul. Even Drekhlo's killing stroke glanced from its fused rune-collar, for the blade has a terrible tally to keep.",
      image: "images/items/furore-normanum.png" },
    { id: "adder-aegis", name: "Adder's Aegis", kind: "Mythic snakescale armor",
      blurb: "Eskil forged for Lüèduó a mail of fine interlocking scales that moves like silk, setting the soul of Kizil Krum into the purple gem at its chest. Such armors are the pride of Persian and Indian princes, meant to move as a cobra does. We see the man's mouth frozen in an eternal scream, a silent testament to the aegis's power.",
      image: "images/items/adder-aegis.png" },
    { id: "demons-bane", name: "Demon's Bane", kind: "Legendary scimitar",
      blurb: "They say this blade was forged in the sacred fires of Vashti's temple, when the demon-sorcerers of Qar threatened to engulf all the world. Bansi's scimitar now bears a crossguard of star-iron and runes that ignite with Freya's-fire against demons and their illusions. Yet even its holy flame could not pierce the hide of the Khan of the Nine Skulls.",
      image: "images/items/demons-bane.png" },
    { id: "vengeance", name: "Vengeance", kind: "Silver-edged scimitar",
      blurb: "Bansi's silver-edged blade, now carried by Rahzalahn, has a sharp and terrible corner. It was this edge the Hound of Tindalos used to tear its way into our world. The Turks of the steppes know well that only such a silver edge can be trusted against shape-shifters and the unquiet dead.",
      image: "images/items/vengeance.png" },
    { id: "ius-dei", name: "Ius Dei", kind: "Masterwork sword",
      blurb: "Eskil reforged the Magyar's cursed flail into a masterwork blade, and with Giovanni's blessing, hammered the evil from its steel. Giovanni first wielded it to run through the Emir in Yellow, dissolving him to seawater. He named it Ius Dei, God's Justice, a term the bishops use for holy violence, which is a thing we have come to understand.",
      image: "images/items/ius-dei.png" },
    { id: "malum", name: "Malum", kind: "Stygian-runed buckler",
      blurb: "Eskil's buckler, forged with the jagged Stygian blade of the Magyar, moves of its own will to parry blows he cannot see. The learned priests of the west would call it Malum — a word that means both apple and evil. It is a cursed thing with a wicked appetite for battle, but it has kept our smith alive.",
      image: "images/items/malum.png" },
    { id: "psalm-singers-sorrow", name: "Psalm-Singer's Sorrow", kind: "Concealed stiletto",
      blurb: "For our priest, Eskil forged a stiletto that deploys from a wrist-bracelet, a hollow-cored needle for holy oil or a faster poison. Only the famed Damascus steel of Khorasan holds such a fine edge. It is the Psalm-Singer's Sorrow, the reluctant, honest weapon of a man of God.",
      image: "images/items/psalm-singers-sorrow.png" },
    { id: "cursed-greatsword", name: "Drekhlo's Greatsword", kind: "Cursed greatsword (penance)",
      blurb: "Drekhlo's greatsword, which punched through Eskil's spine, could not be unmade by fire or hammer. Like the whispering blades of the northern sagas, it speaks to its bearer, tempting him toward his old life in Venice. Giovanni took up this burden as penance, and now carries its murmurs muffled in a runed baldric.",
      image: "images/items/cursed-greatsword.png" },
    { id: "kveld-ulf-dagger", name: "The Kveld-Ulf (Nightwolf Dagger)", kind: "Mythic notched dagger",
      blurb: "Rahzalahn threw Revna's notched dagger to consume the charging Drekhlo, fulfilling one vow and breaking another. Its name, Kveld-Ulf, is that of a saga-wolf of the north, a fitting title for the blade of a Nightwolf Huntress. Eskil's war-blade shattered it to dust at the close of our first journey.",
      image: "images/items/kveld-ulf-dagger.png" },
    { id: "iron-skull", name: "Leif's Iron Skull", kind: "Bound brother-relic",
      blurb: "After Eysýsla, Eskil forged an iron skull and sealed within it the voice of his brother Leif. The skalds sing of such speech-magic, binding one brother's fate to another through runes. Leif's counsel is all that keeps our smith from his own veins.",
      image: "images/items/iron-skull.png" },
    { id: "book-of-eibon", name: "The Book of Eibon (Iban)", kind: "Bound grimoire",
      blurb: "We recovered the pre-Atlantean grimoire from beneath the Khem-Sethi temple, a book whose contents shift after each reading. The Arabs call it the book of Iban, a mishearing of its true name from the Hyperborean cycle. Eskil and Lüèduó once entered it as a place, climbing a stair that defied the senses to retrieve the Ritual of Kavesem.",
      image: "images/items/book-of-eibon.png" },
    { id: "akerke-staff", name: "The Akerke-Staff (Mace of Malice)", kind: "Soul-bound staff",
      blurb: "Eskil took the Stygian staff from Akerke and bound her very spirit into its jet stone, shifting its runes from her script to his. It has become a weapon-prison of the kind seen in Persian and Tibetan tales, where the captor is forever tied to the captive's power. The staff now drains magic from our foes, but her consciousness whispers temptations into Eskil's mind.",
      image: "images/items/akerke-staff.png" },
    { id: "atmashastrum", name: "Atmashastrum (the Dream Knife)", kind: "Spirit weapon",
      blurb: "Lüèduó took up the Dream Knife in the spirit realm, where it appeared in his hand and named him friend of nagas. The yogis of India know of such soul-weapons, or Ātmaśastram, forged of metals from three worlds. With this blade he severed the chain of werewolf-hands binding Sadia, curing her affliction before it vanished with the dawn.",
      image: "images/items/atmashastrum.png" },
    { id: "tiara-tin-tulis", name: "The Tiara of Tin Tulis", kind: "Atlantean storm-crown",
      blurb: "We found the Atlantean storm-crown pinned by a dagger in its maker's tomb, a beacon that called out to dark things. Such crowns are the mark of the sea-queens of old, and its maker's name, Tin Tulis, means 'the hidden one' in the Berber tongue. It burned Bansi's skin until Lucca cloaked its power, and was at last traded for Sadia's cure.",
      image: "images/items/tiara-tin-tulis.png" },
    { id: "atlantean-tablet", name: "The Atlantean Tablet", kind: "High Atlantean inscription",
      blurb: "At the Pillar of Gol-Goroth, we unearthed a stone tablet whose tiny script Lucca at last translated. It speaks of a city consumed in flames, of a rising temple island and a sword-shrine guarded by horror. The Arab geographers whisper of such a sunken city in the ocean past the Pillars of Hercules, a place they name Atlantis.",
      image: "images/items/atlantean-tablet.png" },
    { id: "atlantean-figurine", name: "The Gem-Eyed Figurine", kind: "Atlantean idol",
      blurb: "Lüèduó took the small, gem-eyed figurine from the bishop's burning palace, and it showed him visions of a strange city consumed by fire. We have since seen its squatting, featureless form elsewhere, an icon found in the old lands of the Levant. Lucca required it for her cloaking ritual.",
      image: "images/items/atlantean-figurine.png" },
    { id: "atlantean-signet-ring", name: "The Atlantean Signet Ring", kind: "Mage's signet",
      blurb: "From a buried chest we recovered a signet ring bearing the image of the blank-faced idol. Like the rings of kings and mages in Persian legend, it tested its bearer. The metal resized to fit Lucca's finger, marking her as the Atlantean Mage of the prophecy.",
      image: "images/items/atlantean-signet-ring.png" },
    { id: "atlantean-crystal", name: "The Luminous Crystal of Iram", kind: "Atlantean focus",
      blurb: "We found a pear-sized crystal with the Atlantean tablet, so luminous that a stray sunbeam nearly blinded us all. The mystics of the east use such malakūt-stones to focus moonlight onto a question. Its purpose remains unknown, but we suspect it is the third token marking Lucca as the mage thrice adorned.",
      image: "images/items/atlantean-crystal.png" },
    { id: "self-playing-lute", name: "The Self-Playing Lute", kind: "Djinn-tutored lute",
      blurb: "The lute Lüèduó stole from a courtyard of frozen corpses in Shiraz plays melodies of its own accord. The Arabs tell tales of such djinn-touched instruments, calling them al-ʿūd al-ḥayy, the living oud. We learned a djinn-poet was using it to secretly tutor Rahzalahn, entering her dreams only by her invitation.",
      image: "images/items/self-playing-lute.png" },
    { id: "cursed-amulet", name: "The Cursed Amulet", kind: "Pre-Atlantean amulet",
      blurb: "When Lüèduó seized the amulet from beyond the Iron Gates, the altar bled and the very sack we put it in began to char. The Phoenicians of old used such charms to seal their tomb-portals, a key to wake the dead. Indeed, it fit the lock on Akivasha's crystal sarcophagus and began the Khem-Sethi summoning.",
      image: "images/items/cursed-amulet.png" },
    { id: "silver-hair-comb", name: "Rahzalahn's Silver Hair-Comb", kind: "Silver pin",
      blurb: "Rahzalahn's silver hair-comb, pressed into her hand by Bansi, has found the throats of men and the necks of monsters. Women from the Great Sea to the Persian highlands know such an ornament can be a final, desperate weapon. It now carries the slow, cold weight of every life she has taken with it.",
      image: "images/items/silver-hair-comb.png" },
    { id: "bishop-karols-ring", name: "Bishop Karol's Signet Ring", kind: "Episcopal seal",
      blurb: "We took the signet ring of Bishop Karol from his desecrated abbey, a piece of a life we helped to end. For a bishop in Latin Christendom, this seal authenticates all letters from his see; to lose it is to lose his authority. Now it gives Giovanni a false legitimacy among those who do not know his true history.",
      image: "images/items/bishop-karols-ring.png" },
    { id: "thomas-medallion", name: "The Syriac Thomas Medallion", kind: "Christian relic",
      blurb: "In Kollam, Father Joseph gave Giovanni a small medallion as a token of his community's blessing upon our journey. It bears the Syriac cross of the Thomas Christians, who have kept their faith in India since the apostle first walked these lands.",
      image: "images/items/thomas-medallion.png" },
    { id: "vulture-amulet", name: "Tabiri's Vulture Amulet", kind: "Sekhmet token",
      blurb: "Tabiri of Shendi carries a devotional amulet showing the kneeling, vulture-winged goddess of her people. Such composite goddesses, part lioness and part vulture, are the ancient protectors of the Nubian kingdoms. It was this same iconography she recognized, defaced, above the door of the Khem-Sethi temple.",
      image: "images/items/vulture-amulet.png" },
    { id: "warding-medallion", name: "The Green Chinese-Warding Medallion", kind: "Pre-Han token",
      blurb: "From the bones of a long-dead Tang soldier, we recovered a green stone medallion that recoils from Eskil's cursed blood. Like the recycled charms of the ancient dynasties, its Chinese characters are layered over a much older, unknown script. Giovanni now carries it as a ward against evils it has not yet named.",
      image: "images/items/warding-medallion.png" },
  ],

  lore: [
    { id: "battle-talas", name: "The Battle of Talas (751)", era: "A generation past",
      blurb: "Arab and Tang armies clashed at the Talas River. The Abbasids won. Paper came west; something older came east. The full cost of that trade has not yet been paid." },
    { id: "house-wisdom", name: "The House of Wisdom", era: "Present",
      blurb: "Baghdad's Bayt al-Hikma gathers Greek, Syriac, Persian and Indian learning under one roof. Not all of its translators are mortal, and not all of its books should be opened." },
    { id: "silk-secret", name: "The Secret of Silk", era: "Long past",
      blurb: "Sericulture escaped China in smuggled cane-staves; Khotan and then Byzantium learned the trick. But the original strain — the worm that makes the gold-threaded silk — is still, officially, unique to the Middle Kingdom." },
  ],

  journal: [
    { id: "s01", name: "Session 1 — The Vizier's Letter", date: "Baghdad, Rabī' al-Awwal",
      blurb: "We met in a courtyard off the Tigris. The letter was sealed with a sigil none of us recognized. Tariq read it aloud. By the second paragraph, the lamps had gone out." },
    { id: "s02", name: "Session 2 — The Road to Merv", date: "Khorasan, a month later",
      blurb: "Three days of dust and one night of wolves that were not wolves. Bohemond lost a finger. Zaynab lost her patience with Li Hua's compass." },
    { id: "s03", name: "Session 3 — Under Samarkand", date: "Transoxiana",
      blurb: "The Silent Door opened on the third try. What we found beneath the caravanserai was older than the city, older than the trade. We sealed it again. We will not speak of it in this log." },
    { id: "s04", name: "Session 4 — The Sunday Market", date: "Kashgar",
      blurb: "A dealer in scrolls offered us a map we already owned. When we asked where he got it, he was gone, and the stall was someone else's, and had always been." },
  ],
};
